// src/app/_components/Shrunk/index.tsx
"use client";

import { type ReactNode, useEffect, useState } from "react";

interface Props {
  long?: string;
  short?: string;
  shrink?: number | "portrait";
  hide?: number | "portrait";
  children?: ReactNode;
}

export default function Shrunk({
  long,
  short = long?.split(" ")[0],
  shrink = "portrait",
  hide = 500,
  children,
}: Props) {
  const [shrunk, setShrunk] = useState(false);
  const [hidden, setHidden] = useState(false);

  useEffect(() => {
    function updateTitle() {
      const shouldShrink =
        (shrink === "portrait" && window.innerWidth < window.innerHeight) ||
        window.innerWidth < (shrink as number);

      const shouldHide =
        (shrink === "portrait" && window.innerWidth < window.innerHeight) ||
        window.innerWidth < (hide as number);

      setShrunk(shouldShrink);
      setHidden(shouldHide);
    }

    updateTitle();

    window.addEventListener("resize", updateTitle);
    return () => {
      window.removeEventListener("resize", updateTitle);
    };
  }, [hide, shrink]);

  if (long === undefined) {
    return children;
  } else if (hidden) {
    return null;
  } else if (shrunk) {
    return short;
  } else {
    return long;
  }
}

// src/components/Shrunk/index.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	export let long: string | undefined = undefined;
	export let short: string | undefined = long?.split(' ')[0];
	export let shrink: number | 'portrait' = 'portrait';
	export let hide: number | 'portrait' = 500;

	let shouldShrink = false;
	let hidden = false;

	onMount(() => {
		function updateTitle() {
			if (
				(shrink === 'portrait' && window.innerWidth < window.innerHeight) ||
				window.innerWidth < (shrink as number)
			) {
				if (!shouldShrink) {
					// Disable short title
					// titleDisplay = undefined;
					shouldShrink = true;
				}
			} else if (shouldShrink) {
				// titleDisplay = title;
				shouldShrink = false;
			}

			if (
				(shrink === 'portrait' && window.innerWidth < window.innerHeight) ||
				window.innerWidth < (hide as number)
			) {
				hidden = true;
			} else {
				hidden = false;
			}
		}

		updateTitle();

		window.addEventListener('resize', updateTitle);
		return () => {
			window.removeEventListener('resize', updateTitle);
		};
	});
</script>

<!-- svelte-ignore empty-block -->
{#if long === undefined}
	<slot />
{:else if hidden}{:else if shouldShrink}
	{short}
{:else}
	{long}
{/if}
