// src/components/HeaderLink.svelte
<!-- import type { HTMLAttributes } from 'astro/types';

type Props = HTMLAttributes<'a'>;

const { href, class: className, ...props } = Astro.props;

const { pathname } = Astro.url;
--- -->

<script>
	export let href;
	export let className;

	const { pathname } = Astro.url;
	const isActive = href === pathname || href === pathname.replace(/\/$/, '');
</script>

---
<a {href} class={`${className} ${isActive && 'active'}`}>
	<slot />
</a>

<style lang="scss">
	a {
		display: inline-block;
		text-decoration: none;

		.active {
			font-weight: bolder;
			text-decoration: underline;
		}
	}
</style>

// src/components/HeaderLink.tsx
"use client";

import { AnchorHTMLAttributes, useMemo } from "react";
import { usePathname } from "next/navigation";

import { ProgressBarLink } from "$/components/ProgressBar";

export default function HeaderLink({
  href,
  children,
  ...props
}: AnchorHTMLAttributes<HTMLAnchorElement> & { href: string }) {
  const pathname = usePathname();
  const isActive = useMemo(
    () => href === pathname || href === pathname.replace(/\/$/, ""),
    [href, pathname],
  );

  return (
    <ProgressBarLink
      href={href}
      className={`${props.className || ""} inline-block p-2 decoration-0 active:font-bold active:decoration-1 portrait:text-[3vw]`}
      {...props}
    >
      {children}
    </ProgressBarLink>
  );
}
