// src/components/Header/index.tsx
import Image from 'next/image';
import Link from 'next/link';
import createPersistedState from 'use-persisted-state';
import useSound from 'use-sound';
import {
  type Icon,
  IconClock,
  IconBrandGithub,
  IconBrandTwitch,
  IconBrandTwitter,
  IconBrandLinktree,
  IconBrandMastodon,
  IconHeadphones,
  IconHeadphonesOff,
} from '@tabler/icons-react';
import styles from './index.module.scss';

interface Link {
  name: string;
  url: string;
  emoji: Icon;
  rel?: string;
}

const useAudioEnabled = createPersistedState<boolean>('sound-enabled');

export default function Header() {
  const links: Link[] = [
    {
      emoji: IconBrandGithub,
      name: 'Github',
      url: 'https://github.com/jewlexx',
    },
    {
      emoji: IconBrandTwitch,
      name: 'Twitch',
      url: 'https://twitch.tv/sapphicjewl',
    },
    {
      emoji: IconBrandTwitter,
      name: 'Twitter',
      url: 'https://twitter.com/jewelexx',
    },
    {
      emoji: IconBrandMastodon,
      name: 'Mastodon',
      url: 'https://tech.lgbt/@jewelexx',
      rel: 'me',
    },
    {
      emoji: IconBrandLinktree,
      name: 'Linktree',
      url: 'https://linktr.ee/jewelexx',
    },
  ];

  const [soundEnabled, setSoundEnabled] = useAudioEnabled(true);

  const [clickIn] = useSound('/audio/click-in.mp3', { soundEnabled });
  const [clickOut] = useSound('/audio/click-out.mp3', { soundEnabled });

  return (
    <header className={styles.header}>
      <nav className={styles.nav}>
        <Link className={styles.logolink} href="/" rel="prefetch">
          <Image
            alt="Profile"
            className={styles.monogram}
            priority
            quality={1}
            src="/pfp.jpg"
            width={32}
            height={32}
          />
        </Link>
        {/* <a class="link" href="/projects">Portfolio</a>
		<a class="link" href="/about">About</a> */}
        <Link
          title="Clock link"
          className={styles.social}
          href="/now"
          onMouseEnter={() => clickIn()}
          onMouseDown={() => clickOut()}
        >
          <IconClock />
        </Link>
        {links.map((link) => (
          <a
            title={`${link.name} link`}
            className={styles.social}
            href={link.url}
            key={link.name}
            rel={link.rel}
            onMouseEnter={() => clickIn}
            onMouseDown={() => clickOut()}
          >
            <link.emoji className={styles.socialicon} />
          </a>
        ))}
        <button
          title="Toggle Sound"
          className={styles.audioToggle}
          onMouseEnter={() => clickIn()}
          onClick={() => setSoundEnabled((enabled) => !enabled)}
        >
          {soundEnabled ? <IconHeadphones /> : <IconHeadphonesOff />}
        </button>
      </nav>
    </header>
  );
}

// src/components/Header.svelte
<script lang="ts">
	import {
		IconClock,
		IconBrandGithub,
		IconBrandTwitch,
		IconBrandTwitter,
		IconBrandLinktree,
		IconBrandMastodon
	} from '@tabler/icons-svelte';

	interface Link {
		name: string;
		href: string;
		emoji: any;
		rel?: string;
	}

	const links: Link[] = [
		{
			emoji: IconBrandGithub,
			name: 'Github',
			href: 'https://github.com/jewlexx'
		},
		{
			emoji: IconBrandTwitch,
			name: 'Twitch',
			href: 'https://twitch.tv/sapphicjewl'
		},
		{
			emoji: IconBrandTwitter,
			name: 'Twitter',
			href: 'https://twitter.com/jewelexx'
		},
		{
			emoji: IconBrandMastodon,
			name: 'Mastodon',
			href: 'https://tech.lgbt/@jewelexx',
			rel: 'me'
		},
		{
			emoji: IconBrandLinktree,
			name: 'Linktree',
			href: 'https://linktr.ee/jewelexx'
		}
	];
</script>

<header>
	<nav class="nav">
		<a class="logolink" href="/" rel="prefetch">
			<img alt="Profile" class="monogram" src="/images/pfp-32x.jpg" width={32} height={32} />
		</a>

		<!-- <a class="link" href="/projects">Portfolio</a>
		<a class="link" href="/about">About</a> -->

		{#each links as { href, name, rel, emoji: Emoji }}
			<a class="social" title={`${name} Link`} {href} {rel}>
				<Emoji />
			</a>
		{/each}

		<a class="social" title="The time in seconds" href="/now">
			<IconClock />
		</a>
	</nav>
</header>

<style lang="scss">
	@import '$lib/styles/palette.scss';

	.nav {
		background-color: lighten($dark-gray, 10%);
		display: flex;
		align-items: center;
		padding-top: 1rem;
		padding-right: 2rem;
		padding-bottom: 1rem;
		padding-left: 2rem;
	}

	.logolink {
		display: block;
		color: $t-fg;
		text-decoration: none;
	}

	/* .link {
		color: $t-subdue;
		display: block;
		margin-left: 1rem;
		text-decoration: none;
		font-size: $f-d1;
		text-transform: uppercase;
		padding-top: 0.75em;
		padding-bottom: 0.75em;
		&:focus,
		&:hover {
			color: $t-active;
		}
	} */

	.monogram {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 2em;
		height: 2em;
		margin-right: 0.5rem;
		color: $black;
		font-weight: 900;
		letter-spacing: -0.125rem;
		border: 3px solid currentColor;
		border-radius: 50%;
	}

	.social {
		display: block;
		margin-left: auto;

		@media (prefers-reduced-motion: no-preference) {
			transition: transform 100ms ease-in-out;
		}

		&:hover {
			transform: scale(1.5);
		}

		+ .social {
			margin-left: 0.75rem;
		}
	}
</style>
