// src/app/_components/PubDate/index.tsx
import FormattedDate from "$/app/_components/FormattedDate";

import styles from "./index.module.scss";

interface Props {
  released?: boolean;
  pubDate: Date | undefined;
}

export default function PubDate({ pubDate, released }: Props) {
  if (!pubDate) {
    return null;
  }

  return (
    <p className={styles.pubDate}>
      <i>
        {released ? "Released" : "Published"} on{" "}
        <FormattedDate date={pubDate} />
      </i>
    </p>
  );
}

// src/components/PubDate.svelte
<script lang="ts">
	import FormattedDate from './FormattedDate.svelte';

	interface $$Props {
		pubDate: Date | undefined;
		released?: boolean;
	}
	const { pubDate, released }: $$Props = $props();
</script>

{#if pubDate}
	<small class="text-sm text-gray-800 italic">
		{released ? 'Released' : 'Published'} on <FormattedDate date={pubDate} />
	</small>
{/if}
