// src/components/PubDate/index.tsx
import FormattedDate from "$/components/FormattedDate";

interface Props {
  released?: boolean;
  pubDate: Date | undefined;
}

export default function PubDate({ pubDate, released }: Props) {
  if (!pubDate) {
    return null;
  }

  return (
    <small className="text-sm text-gray-800 italic">
      {released ? "Released" : "Published"} on <FormattedDate date={pubDate} />
    </small>
  );
}

// src/components/PubDate.svelte
<script lang="ts">
	import FormattedDate from './FormattedDate.svelte';

	interface $$Props {
		pubDate: Date | undefined;
		released?: boolean;
	}
	const { pubDate, released }: $$Props = $props();
</script>

{#if pubDate}
	<small class="text-sm text-gray-800 italic">
		{released ? 'Released' : 'Published'} on <FormattedDate date={pubDate} />
	</small>
{/if}
