// src/components/Shield/index.tsx
import Image from "next/image";

import styles from "./index.module.scss";

interface Props {
  enabled?: boolean;
  href?: string;
  // new_tab: boolean;
  src: string;
  alt: string;
  class?: string;
}

export default function Shield({
  enabled = true,
  href,
  src,
  alt,
  class: className,
}: Props) {
  if (!enabled) {
    return null;
  }

  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className={`${styles.shield} ${className}`}
    >
      <img src={src} alt={alt} />
    </a>
  );
}

// src/components/Shield.svelte
<script lang="ts">
	interface $$Props {
		enabled?: boolean;
		href?: string;
		// new_tab: boolean;
		src?: string;
		alt?: string;
		class?: string;
	}
	const { enabled = true, href, src, alt, class: className }: $$Props = $props();
</script>

{#if enabled}
	<a {href} target="_blank" rel="noopener noreferrer" class="mr-2 inline-block {className}">
		<img {src} {alt} />
	</a>
{/if}
