// old-astro/src/components/Stars.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Stars } from '../stars/index';

	let canvas: HTMLCanvasElement;

	onMount(() => {
		const stars = new Stars(canvas);

		stars.beginDrawing();

		return stars.stop;
	});
</script>

<canvas id="stars" bind:this={canvas} />

<style lang="scss">
	#stars {
		position: fixed;
		width: 100vw;
		height: 100vh;
		top: 0;
		left: 0;
		z-index: -1;
	}
</style>

// new-astro/src/components/Stars.tsx
"use client";

import { useEffect, useRef } from "react";

import { Stars as StarsHandler } from "$/stars/index";

export default function Stars() {
  const canvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (!canvas.current) {
      return;
    }

    const stars = new StarsHandler(canvas.current);

    stars.beginDrawing();

    return () => {
      stars.stop();
    };
  }, []);

  return (
    <canvas
      className="fixed top-0 left-0 -z-1 h-screen w-screen"
      ref={canvas}
    />
  );
}
